# Generated by Django 5.0.3 on 2024-03-24 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlightInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=15)),
                ('aviacompany_name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('seats_cnt', models.IntegerField()),
                ('price', models.IntegerField()),
                ('departure', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OrderFlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=15)),
                ('seats_cnt', models.IntegerField()),
                ('flight_date', models.DateField()),
            ],
        ),
    ]
